apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flow-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flow-api
    spec:
      containers:
        - name: api
          image: 864144207131.dkr.ecr.eu-west-2.amazonaws.com/flow-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: '128Mi'
              memory: 500
      imagePullSecrets:
            - name: flow-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flow-api
spec:
  selector:
    app.kubernetes.io/name: flow-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flow-api
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: flow-api
              port:
                number: 80