apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flow-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flow-api
    spec:
      containers:
        - name: api
          image: DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          env:
            - DATABASE_URL: {{ .Values.databaseUrl }}
            - STRIPE_SECRET_KEY: {{ .Values.stripeSecretKey }}
            - STRIPE_WEBHOOK_SECRET: {{ .Values.stripeWebhookSecret }}
            - COGNITO_USER_POOL_ID: {{ .Values.cognitoUserPoolId }}
            - COGNITO_CLIENT_ID: {{ .Values.cognitoClientId }}
            - FLOW_APP_URL: {{ .Values.flowAppUrl }}
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: '128Mi'
              memory: 500
      imagePullSecrets:
            - name: flow-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: flow-api
spec:
  selector:
    app.kubernetes.io/name: flow-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flow-api
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: flow-api
              port:
                number: 80