apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flow-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: flow-api
  provider: aws
  secretObjects:
    - secretName: flow-secrets
      type: Opaque
      data:
        - objectName: dbUrl
          key: flowDbUrl
        - objectName: cognitoUserPoolId
          key: flowCognitoUserPoolId
        - objectName: cognitoClientId
          key: flowCognitoClientId
        - objectName: stripeSecretKey
          key: flowStripeSecretKey
        - objectName: stripeWebhookSecret
          key: flowStripeWebhookSecret
  parameters:
    objects: |
        - objectName: "/flow/rds/DB_URL"
          objectType: "ssmparameter"
          objectAlias: dbUrl
        - objectName: "/flow/cognito/USER_POOL_ID"
          objectType: "ssmparameter"
          objectAlias: flowCognitoUserPoolId
        - objectName: "/flow/cognito/CLIENT_ID"
          objectType: "ssmparameter"
          objectAlias: flowCognitoClientId
        - objectName: "/flow/stripe/SECRET_KEY"
          objectType: "ssmparameter"
          objectAlias: flowStripeSecretKey
        - objectName: "/flow/stripe/WEBHOOK_SECRET"
          objectType: "ssmparameter"
          objectAlias: flowStripeWebhookSecret