name: Flow API Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: flow-api
  IMAGE_TAG: ${{ github.sha }}
  EKS_CLUSTER_NAME: flow-dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assume Role
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/OrganizationAccountAccessRole
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          output-credentials: true
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          DB_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
          COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          FLOW_APP_URL: ${{ secrets.FLOW_APP_URL }}

        run: |
          sed -i.bak "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" "s|DATABASE_URL_VALUE|$DB_URL|g" "s|STRIPE_SECRET_KEY_VALUE|$STRIPE_SECRET_KEY|g" "s|STRIPE_WEBHOOK_SECRET_VALUE|$STRIPE_WEBHOOK_SECRET|g" "s|COGNITO_CLIENT_ID_VALUE|$COGNITO_CLIENT_ID|g" "s|COGNITO_USER_POOL_ID_VALUE|$COGNITO_USER_POOL_ID|g" "s|FLOW_APP_URL_VALUE|$FLOW_APP_URL|g" infra/flow-api.yaml && \
          kubectl apply -f infra/flow-api.yaml
